version: "3.5"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongodb
  # APP*******************************************************************
  springbootapp:
    image: wishlist-products:latest
    build: ./
    restart: always
    container_name: wishlist-products
    expose:
      - "8095"
    ports:
      - "8095:8095"
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongo-data:
